# Generated by Django 5.1.15 on 2026-05-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('references', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.PositiveBigIntegerField(help_text='Price in MNT')),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='km', null=True)),
                ('condition_type', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], default='active', max_length=10)),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, help_text='liters', max_digits=4, null=True)),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('steering', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('pts_status', models.CharField(choices=[('any', 'Any'), ('ok', 'In order'), ('problem', 'Missing or problematic')], default='ok', max_length=10)),
                ('damage_status', models.CharField(choices=[('any', 'Any'), ('ok', 'No repair needed'), ('repair', 'Needs repair or not running')], default='ok', max_length=10)),
                ('seller_type', models.CharField(choices=[('owner', 'Owner'), ('private', 'Private'), ('company', 'Company')], max_length=20)),
                ('availability', models.CharField(choices=[('in_stock', 'In stock'), ('in_transit', 'In transit'), ('on_order', 'On order')], default='in_stock', max_length=20)),
                ('owners_count', models.CharField(blank=True, choices=[('one', 'One'), ('up_to_two', 'Up to two'), ('up_to_three', 'Up to three')], max_length=20, null=True)),
                ('exchange_possible', models.BooleanField(default=False)),
                ('is_certified', models.BooleanField(default=False)),
                ('without_local_mileage', models.BooleanField(default=False, help_text='Not registered in Mongolia / freshly imported')),
                ('customs_cleared', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='references.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='vehicles.brand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='geo.city')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='references.color')),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='references.drivetype')),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='references.fueltype')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vehicles.generation')),
                ('import_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_listings', to='references.country')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='vehicles.model')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='references.transmissiontype')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='vehicles.trim')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
