# Generated by Django 5.1.15 on 2026-05-21 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-published_at'], name='listings_li_status_477a45_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['brand', 'model', 'year'], name='listings_li_brand_i_e9eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_id_682538_idx'),
        ),
    ]
