# Generated by Django 5.1.15 on 2026-05-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_analytics_and_parser_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_view_co_550c8e_idx',
            old_name='listings_li_view_co_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_source_b550ff_idx',
            old_name='listings_li_source_idx',
        ),
        migrations.RenameIndex(
            model_name='listingview',
            new_name='listings_li_listing_7b82c2_idx',
            old_name='listings_li_listing_idx',
        ),
        migrations.RenameIndex(
            model_name='listingview',
            new_name='listings_li_listing_0e8eb2_idx',
            old_name='listings_li_list_ip_idx',
        ),
    ]
