# Generated by Django 5.1.15 on 2026-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rate_to_mnt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='uniq_exchange_rate_currency_date')],
            },
        ),
    ]
